apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-error-page-s
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: error-page-s
  replicas: 1
  template:
    metadata:
      labels:
        app: error-page-s
    spec:
      containers:
      - name: nginx-error-page
        image: kkisilevsky/nginx_error_page
        ports:
        - containerPort: 80
      nodeSelector:
        agentpool: primary
---
apiVersion: v1
kind: Service
metadata:
  name: error-page-s
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: error-page-s