apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: prod-tenant
  source:
    path: public-app
    repoURL: https://github.com/VirtoCommerce/vc-webstore-deploy
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true