apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- storefront-deploy.yaml
- platform-deploy.yaml
- deployment-cm.yaml
- storefront-cm.yaml
- platform-secrets.yaml
- platform-cm.yaml
- ingress-https.yaml

resources:
- ../../common-base
- xapi-deploy.yaml

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: ghcr.io/virtocommerce/platform
  newTag: 3.70.0-master-af7c1a31
- name: docker.pkg.github.com/virtocommerce/vc-storefront/storefront
  newName: ghcr.io/virtocommerce/demo-storefront
  newTag: 1.13.0-alpha.1033-dev-cd9fb156
- name: ghcr.io/virtocommerce/demo-xapi-app
  newName: ghcr.io/virtocommerce/demo-xapi-app
  newTag: 1.0.0-alpha.12-dev
