apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- storefront-deploy.yaml
- platform-deploy.yaml
- deployment-cm.yaml
- storefront-cm.yaml
- platform-secrets.yaml
- platform-cm.yaml
- ingress-https.yaml

resources:
- ../../common-base

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: ghcr.io/virtocommerce/vc-platform/platform
  newTag: 3.67.0-master-1d8965d9
- name: docker.pkg.github.com/virtocommerce/vc-storefront/storefront
  newName: ghcr.io/virtocommerce/demo-storefront
  newTag: 1.13.0-alpha.1033-dev-cd9fb156