apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- storefront-deploy.yaml
- platform-deploy.yaml
- deployment-cm.yaml
- storefront-cm.yaml
- platform-secrets.yaml
- platform-cm.yaml
- ingress-https.yaml
- ingress.yaml

resources:
- ../../common-base

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newTag: 3.39.0-master-251759cc
- name: docker.pkg.github.com/virtocommerce/vc-storefront/storefront
  newName: docker.pkg.github.com/virtocommerce/vc-demo-storefront/demo-storefront
  newTag: demo-storefront:1.10.0-alpha.1009-upstream-dev-f449e64f
