apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 2
  template:
    metadata:
        annotations:
          reloader.stakater.com/search: "true"
          configmap.reloader.stakater.com/reload: "webstore-platform-cm, webstore-deployment-cm, webstore-platform-secret-configmap"
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/agent-pre-populate-only: "true"
          vault.hashicorp.com/agent-configmap: "webstore-platform-secret-configmap"
          vault.hashicorp.com/agent-requests-cpu: "25m"
          vault.hashicorp.com/agent-limits-cpu: "50m"   
    spec:
      initContainers:
        - name: init-sqldatabase
          env:
            - name: VC_SAMPLE_DATA_DB
              value: webstore-platform_source
        - name: init-platform
          imagePullPolicy: Always
          image: docker.pkg.github.com/virtocommerce/vc-deploy-containers/platform-installer:v3
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "echo START INIT $(date +%Y-%m-%d-%H-%M-%S)
            && python3 install-modules.py \"$MODULES_CONFIG\" /mnt/Modules/*
            && python3 installer.py $(ELECTRONICS_THEME_URL) $(ELECTRONICS_THEME_LOCATION)
            && python3 installer.py $(B2B_THEME_URL) $(B2B_THEME_LOCATION)
            && python3 installer.py $(ASSETS_URL) $(ASSETS_LOCATION)"
      containers:
        - name: vc-platform-web
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          envFrom:
          - configMapRef:
              name: platform-cm
          - configMapRef:
              name: platform-overlay-config
      nodeSelector:
        agentpool: applications
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

          
