apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
namePrefix: webstore-
commonLabels:
  instance: webstore

resources:
- ../../resources

configMapGenerator:
- name: db-config
  literals:
    - VC_DB_HOST=vc-prod-dbserver.database.windows.net
    - VC_DB=vc-prod-dbserver
    - VC_DB_POOL=vc-prod-elasticpool
    - VC_DB_USER=virto
- name: overlay-config
  literals:
    - APPINSIGHTS_INSTRUMENTATIONKEY="f60031ba-a752-4178-90b3-4bf05b631a19"

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        agentpool: applications
  target:
    group: apps
    version: v1
    kind: Deployment

vars:
- name: VC_DB_HOST
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB_HOST']
- name: VC_DB
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB']
- name: VC_DB_POOL
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB_POOL']
- name: VC_DB_USER
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB_USER']