apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      annotations:
        reloader.stakater.com/search: "true" 
        configmap.reloader.stakater.com/reload: "platform-cm,storefront-cm,deployment-cm"
      labels:
        app: storefront
    spec:
      initContainers:
        - name: init-storefront
          imagePullPolicy: Always
          image: docker.pkg.github.com/virtocommerce/vc-deploy-containers/platform-installer:dev-test
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "python3 installer.py $(ELECTRONICS_THEME_URL) $(ELECTRONICS_THEME_LOCATION)
            && python3 installer.py $(B2B_THEME_URL) $(B2B_THEME_LOCATION)
            && python3 installer.py $(ASSETS_URL) $(ASSETS_LOCATION)"
          envFrom:
          - configMapRef:
              name: deployment-cm 
          volumeMounts:
            - mountPath: /mnt/cms-content
              name: cms-content-data
      containers:
      - name: vc-storefront-web
        image: docker.pkg.github.com/virtocommerce/vc-storefront/storefront:dev-linux-latest
        envFrom:
        - configMapRef:
            name: storefront-cm
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /opt/virtocommerce/storefront/wwwroot/cms-content
          name: cms-content-data
      volumes:
      - name: cms-content-data
        persistentVolumeClaim:
          claimName: cms-content-volume