apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vc-platform-web
          resources:
            requests:
              memory: "512Mi"
              cpu: 150m
            limits:
              memory: "1024Mi"
              cpu: 300m
          command:
            - "/bin/bash"
            - "-c"
          args:
            - "dotnet VirtoCommerce.Platform.Web.dll"
      volumes:
      - name: cms-content-data
        persistentVolumeClaim:
          claimName: cms-content-volume-paas
