apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vc-platform-web
          resources:
            requests:
              memory: "512Mi"
              cpu: 350m
            limits:
              memory: "1024Mi"
              cpu: 1000m
          
