---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume-paas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  storageClassName: "blob-paas-nfs"