$patch: delete
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-content
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Mi
  csi: {}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: "blob-premium"
---
$patch: delete
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi
  storageClassName: "blob-paas-nfs"