apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo
namePrefix: public-
commonLabels:
  instance: public

patchesStrategicMerge:
- storefront-deploy.yaml
- platform-deploy.yaml
- deployment-cm.yaml
- platform-cm.yaml
- storefront-cm.yaml
- ./traefik/ingress.yaml
- ./traefik/ingress-https.yaml
resources:
- ../common-base/public
- ./traefik/middleware-errors.yaml
- ./traefik/middleware-rewrite.yaml
#- kube-job.yaml
images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newTag: 3.35.0-master-d0f77ea9
- name: docker.pkg.github.com/virtocommerce/vc-storefront/storefront
  newName: docker.pkg.github.com/virtocommerce/vc-demo-storefront/demo-storefront
  newTag: 1.6.0-master-dec77890

configMapGenerator:
- name: db-config
  literals:
    - VC_DB_HOST=vc-prod-dbserver.database.windows.net
    - VC_DB=vc-prod-dbserver
    - VC_DB_POOL=vc-prod-elasticpool
    - VC_DB_USER=virto

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        agentpool: applications
  target:
    group: apps
    version: v1
    kind: Deployment

vars:
- name: VC_DB_HOST
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB_HOST']
- name: VC_DB
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB']
- name: VC_DB_POOL
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB_POOL']
- name: VC_DB_USER
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data['VC_DB_USER']
  