apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: "myapp"
        reloader.stakater.com/search: "true"
        configmap.reloader.stakater.com/reload: "public-platform-cm, public-deployment-cm, public-platform-secret-configmap"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-configmap: "public-platform-secret-configmap"
        vault.hashicorp.com/agent-requests-cpu: "25m"
        vault.hashicorp.com/agent-limits-cpu: "50m"
    spec:
      initContainers:
        - name: init-platform
          image: docker.pkg.github.com/virtocommerce/vc-deploy-containers/platform-installer:v2
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "echo START INIT $(date +%Y-%m-%d-%H-%M-%S)
            && python3 install-modules.py \"$MODULES_CONFIG\" /mnt/Modules/*
            && if [ ! -d \"$ELECTRONICS_THEME_LOCATION\" ]; then mkdir -p \"$ELECTRONICS_THEME_LOCATION\"; fi
            && rm -rf $(ELECTRONICS_THEME_LOCATION)/*
            && python3 install-theme.py $(ELECTRONICS_THEME_URL) $(ELECTRONICS_THEME_LOCATION)
            && echo ELECTRONICS THEME INSTALLED $(date +%Y-%m-%d-%H-%M-%S)
            && if [ ! -d \"$B2B_THEME_LOCATION\" ]; then mkdir -p \"$B2B_THEME_LOCATION\"; fi
            && rm -rf $(B2B_THEME_LOCATION)/*
            && python3 install-theme.py $(B2B_THEME_URL) $(B2B_THEME_LOCATION)
            && echo B2B THEME INSTALLED $(date +%Y-%m-%d-%H-%M-%S)
            && if [ -d /mnt/cms-content/assets ]; then rm -rf /mnt/cms-content/assets; fi
            && python3 upload-assets.py $(ASSETS_URL) $(ASSETS_LOCATION)
            && echo ASSETS INSTALLED $(date +%Y-%m-%d-%H-%M-%S)"
        - name: init-sqldatabase
          image: mcr.microsoft.com/mssql-tools
          env:
            - name: VC_SAMPLE_DATA_DB
              value: public-platform_demo_src
      containers:
        - name: vc-platform-web
          command:
            - "/bin/bash"
            - "-c"
          args:
            - "sleep 3m && dotnet VirtoCommerce.Platform.Web.dll"