apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: "myapp"
        reloader.stakater.com/search: "true"
        configmap.reloader.stakater.com/reload: "public-platform-cm, public-deployment-cm, public-platform-secret-configmap"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-configmap: "public-platform-secret-configmap"
        vault.hashicorp.com/agent-requests-cpu: "25m"
        vault.hashicorp.com/agent-limits-cpu: "50m"
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      initContainers:
        - name: init-sqldatabase
          image: mcr.microsoft.com/mssql-tools
          env:
            - name: VC_SAMPLE_DATA_DB
              value: public-platform_demo_src
        - name: init-platform
          imagePullPolicy: Always
          image: ghcr.io/virtocommerce/vc-deploy-containers/platform-installer:v3
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "echo START INIT $(date +%Y-%m-%d-%H-%M-%S)
            && python3 install-modules.py \"$MODULES_CONFIG\" /mnt/Modules/* && export RM_PREFIX=/*
            && if [ -d \"$ELECTRONICS_THEME_LOCATION\" ]; then rm -rf \"$ELECTRONICS_THEME_LOCATION$RM_PREFIX\"; fi
            && python3 installer.py $(ELECTRONICS_THEME_URL) $(ELECTRONICS_THEME_LOCATION)
            && if [ -d \"$B2B_THEME_LOCATION\" ]; then rm -rf \"$B2B_THEME_LOCATION$RM_PREFIX\"; fi
            && python3 installer.py $(B2B_THEME_URL) $(B2B_THEME_LOCATION)
            && if [ -d \"$ASSETS_LOCATION\" ]; then rm -rf \"$ASSETS_LOCATION$RM_PREFIX\"; fi
            && python3 installer.py $(ASSETS_URL) $(ASSETS_LOCATION)"
      containers:
        - name: vc-platform-web
          readinessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
          command:
            - "/bin/bash"
            - "-c"
          args:
            - "source /vault/secrets/config_base && source /vault/secrets/config_custom && sleep 3m && dotnet VirtoCommerce.Platform.Web.dll" 